repos:
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: cmd /C '[python_interpreter] freeze > requirements.txt && git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]