version: '3.5'
services:

  web:
    build: .
    container_name: "streamlit_app"
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0 --server.runOnSave=true
    volumes:
      - .:/app
    env_file: .env
    restart: always
    ports:
      - "8502:8501"
    stdin_open: true
    tty: true
    depends_on:
        - redis_streamlit_app
    networks:
      - api_network

  redis_streamlit_app:
    image: "redis:latest"
    container_name: "redis_streamlit_app"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET}
